### ISSUE TITLE
Styling the page

### ISSUE THREAD

**Issue by ujjwalkirti** [utkarsh-atom/Simple-Interest-Calculator#1]
The way you have written JavaScript is very unconventional and not preferred.

I have revamped the whole code in terms of functionality and logic, please take a look and try to understand what I have done.

I have tried some basic styling, like changing the fonts and all but a still lot is required if we want to make it look good.

Tasks:

1. Make the calculator area look like a card, for example provide it with shadows and opacity.
2. Add background gradient
3. Add links to your social media accounts in the footer

That is it for now!

**Comment by utkarsh-atom** [comment]
Thanks
